### ISSUE TITLE
errors when using conda to install r 

### ISSUE THREAD

**Issue by chazdm** [plotly/orca#109]
Hello,

I've been trying to install r and keep getting the following error message. Not sure how to proceed. Appreciate any assistance. Thank you!

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/cdmelloc/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/export/home/cdmelloc/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/export/home/cdmelloc/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/export/home/cdmelloc/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/export/home/cdmelloc/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/export/home/cdmelloc/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 336, in install
    minimal_hint=args.alt_hint)
  File "/export/home/cdmelloc/anaconda/lib/python2.7/site-packages/conda/plan.py", line 397, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/export/home/cdmelloc/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 739, in solve
    minimal_hint=minimal_hint)
  File "/export/home/cdmelloc/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 507, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/export/home/cdmelloc/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: r-base-3.3.1-6.tar.bz2 MatchSpec(u'_r-mutex 1.* anacondar_1')

**Comment by etpinard** [comment]
Closing. @chazdm feel free to open a new issue if you're still having problem install orca with the latest installation instructions:

https://github.com/plotly/orca#installation

Thank you.
