### ISSUE TITLE
xvfb-run: error: Xvfb failed to start

### ISSUE THREAD

**Issue by lobachevzky** [plotly/orca#131]
I am able to reproduce the error with the following minimal code:
```
import plotly.io as pio
import numpy as np
import plotly.graph_objs as go


N = 100
x = np.random.rand(N)
y = np.random.rand(N)
colors = np.random.rand(N)
sz = np.random.rand(N)*30

fig = go.Figure()
fig.add_scatter(x=x,
                y=y,
                mode='markers',
                marker={'size': sz,
                        'color': colors,
                        'opacity': 0.6,
                        'colorscale': 'Viridis'})

pio.write_image(fig, 'plot.png')
```
To which I get the following error:
```
❯ python orca_bug.py 
Traceback (most recent call last):
  File "orca_bug.py", line 21, in <module>
    pio.write_image(fig, 'plot.png')
  File "/home/ethanbro/virtualenvs/598/lib/python3.6/site-packages/plotly/io/_orca.py", line 1492, in write_image
    validate=validate)
  File "/home/ethanbro/virtualenvs/598/lib/python3.6/site-packages/plotly/io/_orca.py", line 1263, in to_image
    ensure_server()
  File "/home/ethanbro/virtualenvs/598/lib/python3.6/site-packages/plotly/io/_orca.py", line 1134, in ensure_server
    validate_executable()
  File "/home/ethanbro/virtualenvs/598/lib/python3.6/site-packages/plotly/io/_orca.py", line 1001, in validate_executable
    returncode=p.returncode))
ValueError: 
The orca executable is required in order to export figures as static images,
but the executable that was found at '/usr/local/bin/orca'
does not seem to be a valid plotly orca executable. Please refer to the end of
this message for details on what went wrong.

If you haven't installed orca yet, you can do so using conda as follows:

    $ conda install -c plotly plotly-orca

Alternatively, see other installation methods in the orca project README at
https://github.com/plotly/orca.

After installation is complete, no further configuration should be needed. 

If you have installed orca, then for some reason plotly.py was unable to
locate it. In this case, set the `plotly.io.orca.config.executable`
property to the full path of your orca executable. For example:

    >>> plotly.io.orca.config.executable = '/path/to/orca'

After updating this executable property, try the export operation again.
If it is successful then you may want to save this configuration so that it
will be applied automatically in future sessions. You can do this as follows:

    >>> plotly.io.orca.config.save() 

If you're still having trouble, feel free to ask for help on the forums at
https://community.plot.ly/c/api/python

An error occurred while trying to get the version of the orca executable.
Here is the command that plotly.py ran to request the version
    $ /usr/local/bin/orca --version

This command returned the following error:

[Return code: 1]
xvfb-run: error: Xvfb failed to start
```
I am running headless so I use `xvfb-run`:
```
❯ cat $(which orca)
#!/bin/zsh

xvfb-run /usr/local/lib/node_modules/orca/orca-1.1.1-x86_64.AppImage "$@"
```
Using Ubuntu 18:
```
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
Weirdly, I do not get the error when I run ` /usr/local/bin/orca --version`:
```
❯  /usr/local/bin/orca --version
desktop-file-install is missing. Skipping /tmp/.mount_orca-1Pimrny/AppRun.
1.1.1
```
Not sure what the other stuff is about.

**Comment by hstocks** [comment]
`xvfb-run` hides errors by default, so you need to explicitly tell it to show the error.

Try this in your orca script:
```xvfb-run -e /dev/stdout /usr/local/lib/node_modules/orca/orca-1.1.1-x86_64.AppImage "$@"```

**Comment by etpinard** [comment]
I suspect the `orca` in your path is GNOME's orca, not plotly's. What does 

```
$ orca --help
```

output for you?

**Comment by lobachevzky** [comment]
```
❯ orca --help
desktop-file-install is missing. Skipping /tmp/.mount_orca-1zieAbT/AppRun.
Plotly's image-exporting utilities

  Usage: orca [--version] [--help] <command> [<args>]

  Available commands:
  - graph [or plotly-graph, plotly_graph]
    Generates an image of plotly graph from inputted plotly.js JSON attributes.
    For more info, run `orca graph --help`.
  - serve [or server]
    Boots up a server with one route per available export component
    For more info, run `orca serve --help`
```

**Comment by etpinard** [comment]
and what about `$ which orca`?

**Comment by lobachevzky** [comment]
```
 ❯ which orca
/usr/local/bin/orca
```

**Comment by lobachevzky** [comment]
Also @hstocks 
```
❯ xvfb-run -e /dev/stdout /usr/local/lib/node_modules/orca/orca-1.1.1-x86_64.AppImage "$@"
desktop-file-install is missing. Skipping /tmp/.mount_orca-1PJUgBC/AppRun.
Plotly's image-exporting utilities

  Usage: orca [--version] [--help] <command> [<args>]

  Available commands:
  - graph [or plotly-graph, plotly_graph]
    Generates an image of plotly graph from inputted plotly.js JSON attributes.
    For more info, run `orca graph --help`.
  - serve [or server]
    Boots up a server with one route per available export component
    For more info, run `orca serve --help`.
```

**Comment by etpinard** [comment]
and does

```
xvfb-run orca graph '{ "data": [{"y": [1,2,1]}] }' -o fig.png
```

work for you?

-----------

**Comment by lobachevzky** [comment]
```
❯ xvfb-run -e orca graph '{ "data": [{"y": [1,2,1]}] }' -o fig.png
/usr/bin/xvfb-run: 184: /usr/bin/xvfb-run: graph: not found
```

**Comment by etpinard** [comment]
abd what about 

```
xvfb-run orca graph '{ "data": [{"y": [1,2,1]}] }' -o fig.png
```

minus the `-e`?

**Comment by lobachevzky** [comment]
```
❯ xvfb-run orca graph '{ "data": [{"y": [1,2,1]}] }' -o fig.png
xvfb-run: error: Xvfb failed to start
```

**Comment by hstocks** [comment]
Remove the `--help` from the command you ran in response to my comment.
i.e. do ` xvfb-run -e /dev/stdout /usr/local/lib/node_modules/orca/orca-1.1.1-x86_64.AppImage`

**Comment by lobachevzky** [comment]
```
❯ xvfb-run -e /dev/stdout /usr/local/lib/node_modules/orca/orca-1.1.1-x86_64.AppImage
desktop-file-install is missing. Skipping /tmp/.mount_orca-1iNV0md/AppRun.
Plotly's image-exporting utilities

  Usage: orca [--version] [--help] <command> [<args>]

  Available commands:
  - graph [or plotly-graph, plotly_graph]
    Generates an image of plotly graph from inputted plotly.js JSON attributes.
    For more info, run `orca graph --help`.
  - serve [or server]
    Boots up a server with one route per available export component
    For more info, run `orca serve --help`.
```

**Comment by Ejdamm** [comment]
Try put the -a flag in /usr/local/bin/orca and then try to run your code again.
`xvfb-run -a /usr/local/lib/node_modules/orca/orca-1.1.1-x86_64.AppImage "$@"`

**Comment by lobachevzky** [comment]
```
❯ xvfb-run -a /usr/local/lib/node_modules/orca/orca-1.1.1-x86_64.AppImage "$@"


desktop-file-install is missing. Skipping /tmp/.mount_orca-1vcTLBT/AppRun.
Plotly's image-exporting utilities

  Usage: orca [--version] [--help] <command> [<args>]

  Available commands:
  - graph [or plotly-graph, plotly_graph]
    Generates an image of plotly graph from inputted plotly.js JSON attributes.
    For more info, run `orca graph --help`.
  - serve [or server]
    Boots up a server with one route per available export component
    For more info, run `orca serve --help`.
```

**Comment by Ejdamm** [comment]
That is the result I get when I run the command directly in the terminal but that is not what it is meant for. Did you put it in /usr/local/bin/orca?

**Comment by lobachevzky** [comment]
Ah sorry for misreading. That actually fixed it. What does `-a` do?

**Comment by Ejdamm** [comment]
Manpages says 

> -a, --auto-servernum
>               Try to get a free server number, starting at 99, or the argument to --server-num.

So if there is already a xvfb-instance running and the -a flag is not set they will both try to connect with server number 99. With the -a flag enabled the second instance will try to get server number 100++ instead.

I also use headless ubuntu 18.04 and had the same problem. I tracked it down to validate_executable() in _orca.py (https://github.com/plotly/plotly.py/blob/master/plotly/io/_orca.py#L841).
It validates the orca executable by first calling `orca --help` and then `orca --version` directly after. If they are run with xfvb the first run will go well but it doesn't have enough time to exit before the second is called, So `orca --version` tries to connect with servernumber 99 which is already taken and returns an error, making orca believe the wrong orca executable is installed.

**Comment by lobachevzky** [comment]
Not directly related to this bug, but for some reason I get
```
❯ man orca
No manual entry for orca
See 'man 7 undocumented' for help when manual pages are not available.
```

**Comment by avinashshenoy97** [comment]
I need help too :(

```
> ubuntu@ip-172-31-17-255:~$ xvfb-run -e /dev/stdout /home/ubuntu/orca-1.2.1-x86_64.AppImage -a
desktop-file-install is missing. Skipping /tmp/.mount_orca-1YVhKRx/AppRun.
/tmp/.mount_orca-1YVhKRx/app/orca: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory```
